version: '1'
environment: production
cloud: aws
overrides: {}
custom_services: []
exclusions:
  hosts: []
  labels: {}
scan:
  timeout_seconds: 30
  port_scan_enabled: false
  cidr_ranges: []
_activated_scan_id: 9dc7683c-e202-4b44-84d4-d1d831f94ca5
_activated_at: '2026-05-13T06:16:37.189912'
_activated_resource_count: 8
